// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trellobot.Model;

namespace trellobot.Migrations
{
    [DbContext(typeof(TrellobotContext))]
    [Migration("20190120115735_MemberTableRemoved")]
    partial class MemberTableRemoved
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("trellobot.Model.TrellobotItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoardId");

                    b.Property<int?>("MemberID");

                    b.Property<string>("Name");

                    b.Property<string>("TemplateId");

                    b.HasKey("ID");

                    b.HasIndex("MemberID");

                    b.ToTable("TrellobotItems");
                });

            modelBuilder.Entity("trellobot.Model.TrellobotMember", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemberName");

                    b.Property<string>("Token");

                    b.Property<string>("TrelloID");

                    b.Property<string>("fullName");

                    b.Property<string>("initials");

                    b.HasKey("MemberID");

                    b.ToTable("TrellobotMembers");
                });

            modelBuilder.Entity("trellobot.Model.TrellobotItem", b =>
                {
                    b.HasOne("trellobot.Model.TrellobotMember", "TrellobotMember")
                        .WithMany("TrellobotItems")
                        .HasForeignKey("MemberID");
                });
#pragma warning restore 612, 618
        }
    }
}
