// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trellobot.Model;

namespace trellobot.Migrations
{
    [DbContext(typeof(TrellobotContext))]
    [Migration("20190120120253_MemberTableRemovedForReal")]
    partial class MemberTableRemovedForReal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("trellobot.Model.TrellobotItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoardId");

                    b.Property<string>("Name");

                    b.Property<string>("TemplateId");

                    b.Property<string>("Token");

                    b.HasKey("ID");

                    b.ToTable("TrellobotItems");
                });
#pragma warning restore 612, 618
        }
    }
}
